home-work
ddryzhov/book-store pull request #3
Opened 2024-04-14 06:20 UTC by ddryzhov

Replaced the existing BookRepository with JpaRepository, added Liquibase support, changed spring.jpa.hibernate.ddl-auto property value to validate, implemented soft delete concept, added put and delete endpoints

2024-04-14 10:37 UTC, okuzan requested changes
extract /api to project-wide prefix (use application.properties)

2024-04-14 10:37 UTC, okuzan commented on src/main/java/mate/academy/bookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
where is deperacted, replace with SQLRestriction
uppercase true and false 
```suggestion
@SQLRestriction("is_deleted = FALSE")
```

2024-04-14 14:36 UTC, MAMentorFX requested changes

2024-04-14 14:36 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +    public BookDto update(Long id, BookDto bookDto) {
@Transactional. You make more than one call to DB

2024-04-14 14:36 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +        existingBook.setPrice(bookDto.getPrice());
use MapStruct

2024-04-15 14:16 UTC, olekskov approved these changes

2024-04-17 21:33 UTC, merged