home-work
ddryzhov/book-store pull request #6
Opened 2024-05-31 17:43 UTC by ddryzhov

added Pagination, Sorting, and Swagger

2024-05-31 19:17 UTC, okuzan approved these changes

2024-06-07 10:58 UTC, ddryzhov commented
See last commit, sorry, I just forgot to merge the previous commit

2024-06-07 11:10 UTC, Elena-Bruyako requested changes
Let's fix some comments

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/user/UserRegistrationRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```
It's better for String. check other places

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @NotNull
```suggestion
```

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @NotNull
Check other places

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @Size(min = 8)
You can use length property in Column annotation instead of Size

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +
remove blank lines

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @Column(name = "first_name", nullable = false)
Don't need to specify the name, Hibernate automatically creates name with snake_case

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/validation/FieldMatchValidator.java
> +            Object firstValue = BeanUtils.getProperty(value, firstFieldName);
Or use can use Spring BeanWrapperImpl and remove org.apache.commons.beanutils dependency
`Object firstValue = new BeanWrapperImpl(value).getPropertyValue(this. firstFieldName);`

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/validation/FieldMatchValidator.java
> +            return firstValue != null && firstValue.equals(secondValue);
```suggestion
            return Objects.equals(firstValue, secondValue);
```

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-user-table.yaml
> +            tableName: user
```suggestion
            tableName: users
```

2024-06-07 11:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +@Table(name = "user")
```suggestion
@Table(name = "users")
```
Table name should be plural according to the naming convention

2024-06-07 15:13 UTC, merged