Temp branch
ddryzhov/book-store pull request #7
Opened 2024-06-07 15:20 UTC by ddryzhov

Added User entity, the required DTOs and mapper, AuthenticationController, use data validation in the new DTO classes, Added FieldMatch annotation, RegistrationException using the GlobalExceptionHandler

2024-06-07 18:24 UTC, Elena-Bruyako requested changes
Let's fix some comments

2024-06-07 18:24 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @NotBlank
Let's use one of annotations NotBlank or Column(nullable = false) 
https://www.baeldung.com/hibernate-notnull-vs-nullable

2024-06-07 18:24 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-user-table.yaml
> +      id: create-user-table
```suggestion
      id: create-users-table
```

2024-06-08 05:20 UTC, Elena-Bruyako requested changes
Last comment to consider

2024-06-08 05:20 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @NotBlank
Got your choice) 
But, we still need email = unique

2024-06-08 11:06 UTC, Vasul-Pankiv approved these changes

2024-06-09 17:00 UTC, merged